Better reroll support and more rolling functions
reecer62/dice-wench pull request #5
Opened 2019-08-26 05:04 UTC by Grissess

2019-08-26 13:06 UTC, Grissess commented on index.js
> +        msg.channel.send('Error: incorrect format!\nFormat: `!quoteadd "<quote text>" -<name>`')
The web UI definitely got me here.

After merging, you should definitely lint/format this. This part should be an easy catch.

2019-08-27 04:53 UTC, reecer62 commented on index.js
> +        msg.channel.send('Error: incorrect format!\nFormat: `!quoteadd "<quote text>" -<name>`')
I'll lint this so hard

2019-08-27 05:35 UTC, reecer62 requested changes
Remove dead code

2019-08-30 01:42 UTC, Grissess commented
Sorry, your request for changes must have gotten eaten--I only noticed it today :P

2019-08-31 05:38 UTC, reecer62 approved these changes

2019-09-01 03:20 UTC, merged